services:
  backend:
    build: .
    container_name: job-tracker-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: job-tracker-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:

